name: Flake8 and yapf

on:
 push:
   branches: [ main ]
 pull_request:
   branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        pip install flake8
        pip install yapf
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings.
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=120 --statistics
    - name: yapf
      id: yapf
      uses: diegovalenzuelaiturra/yapf-action@v0.0.1
      with:
        args: . --recursive --diff
    - name: Fail if yapf made changes
      if: steps.yapf.outputs.exit-code == 2
      run: exit 1
