name: Python conda test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Initialize Conda
      run: |
        echo "shell: ${SHELL}"
        conda init "$(basename ${SHELL})"
        echo "path: $PATH"
    - uses: actions/checkout@v2
    - uses: goanpeca/setup-miniconda@v1
      with:
         activate-environment: livelossplot
         environment-file: environment.yml
         python-version: 3.5
         auto-activate-base: false
    - shell: bash -l {0}
      run: |
        conda info
        conda list
    - name: Lint with flake8
      shell: bash -l {0}
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      shell: bash -l {0}
      run: |
        pytest
